### ISSUE TITLE
lower sound effects/theme volume

### ISSUE THREAD

**Issue by afonso-tsx** [rayden-61/stepp1-plus#2]
hi, great work on the project :) 
is there a way to individually change the theme/sfx volume from the song volume?

**Comment by rayden-61** [comment]
unfortunately not, but you can access all sound files on .\stepp1-plus\Themes\Fiesta 2\Sounds\Sounds and use a tool like audacity to edit the sound files and lower their volumes.

**Comment by afonso-tsx** [comment]
thanks I will do that :)
