### ISSUE TITLE
No loading\stage break screen.

### ISSUE THREAD

**Issue by Excel73** [rayden-61/stepp1-plus#6]
When you get the god-forsaken "Hey, why don't you just get up and dance, man?", the audio plays but the actual screen doesn't show at all, just a black screen. This also occurs with the loading screens, just black.

**Comment by rayden-61** [comment]
This is working as intended, all the fake loading screens were removed for faster gameplay resume after failing or exiting out of a song

**Comment by Excel73** [comment]
Is there a way that I can re-add them?

**Comment by rayden-61** [comment]
It's very easy to re-add them. If you look at the commit history, this is one of the first things that was done, so just take a look at the code changes and try to track the references to those images and videos. The initial commit which is just StepP1 1.0.3 still has all of them.

**Comment by Excel73** [comment]
Thanks, I'll check it out.

**Comment by Excel73** [comment]
Also, great work on the project! You're the hero in the pump community we
all needed for a definitive PC PIU experience!
